app/models/animal.rb, app/models/catch.rb, app/models/collection.rb, app/models/taxonomy.rb, app/models/user.rb
Models Associations : 
- user
- catch
- collection
- animal
- taxonomy
=> modal associations

app/models/animal.rb, app/models/badge.rb, app/models/catch.rb, app/models/collection.rb, app/models/friendship.rb, app/models/taxonomy.rb, app/models/user.rb
Model validations:
- user
- taxonomy
- friendship
- collection
- catch
- badge
- animal
=> model validations

db/migrate/20230606065817_add_index_to_users.rb, db/schema.rb
Users table:
Index added to username
=> index added to username in users table

app/controllers/pages_controller.rb
Skip and only home removed from pages controller
=> skip removed from pages controller

.gitignore, Gemfile, Gemfile.lock, app/models/animal.rb, app/models/badge.rb, app/models/catch.rb, app/models/user.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/storage.yml, db/migrate/20230606105906_create_active_storage_tables.active_storage.rb, db/schema.rb
cloudinary and active records installed
models updated with has_one_attached :photo
- badge
- catch
- user
=> Cloudinary active records

db/migrate/20230606111416_add_photo_to_animals.rb, db/schema.rb
column photo_url added to animals table
=> photo animals added to table

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/controllers/pages_controller.rb, app/views/pages/style.html.erb, config/routes.rb
=> style in progress

app/controllers/animals_controller.rb, app/controllers/badges_controller.rb, app/controllers/catches_controller.rb, app/controllers/collections_catches_controller.rb, app/controllers/collections_controller.rb, app/controllers/friendships_controller.rb, app/controllers/got_badges_controller.rb, app/controllers/taxonomies_controller.rb, app/controllers/users_controller.rb, app/models/collections_catch.rb, test/controllers/animals_controller_test.rb, test/controllers/badges_controller_test.rb, test/controllers/catches_controller_test.rb, test/controllers/collections_catches_controller_test.rb, test/controllers/collections_controller_test.rb, test/controllers/friendships_controller_test.rb, test/controllers/got_badges_controller_test.rb, test/controllers/taxonomies_controller_test.rb, test/controllers/users_controller_test.rb
Controllers generated:
- Users
- Taxonomies
- Friendships
- Animals
- Badges
- Catches
- Collections
- Got_badges
- Collections_catches
=> Controllers generation

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/models/friendship.rb, app/views/pages/style.html.erb
Mistake fixed with an extra comma in friendship model
=> Friendship issue

.gitignore, app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/policies/user_policy.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/pages/show.html.erb, test/controllers/users_controller_test.rb, test/policies/user_policy_test.rb
-application-controller: autoriser au signup et à l'update.
-user registration view (new et edit): images + username.
-Pundit policy du user générée
-users_controller : fonction show créer
-user_policy : show policy faite
=> Usercontroller

app/views/friends/show.html.erb
=> fix friend show issue

app/views/collections/_catches_collection.html.erb, app/views/collections/_display_animals.html.erb
=> Fix catch photo

app/assets/stylesheets/components/_cards.scss, app/javascript/controllers/index_collection_controller.js, app/javascript/controllers/show_collection_controller.js, app/views/collections/_catches_collection.html.erb, app/views/collections/_display_animals.html.erb, app/views/collections/_form_create.html.erb, app/views/collections/_form_edit.html.erb, app/views/collections/general.html.erb, app/views/collections/index.html.erb, app/views/collections/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_cards_collection.html.erb, app/views/shared/_cards_general_collection.html.erb
issues with collections edit and add catches fixed
=> fix display collections

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_trash.scss, app/assets/stylesheets/components/_trash_bin.scss, app/views/collections/_catches_collection.html.erb, app/views/collections/show.html.erb
remove delete button on catches in general collection
remove add and edit buttons on general collection
few css added
=> Front collection

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_cards.scss, app/javascript/controllers/show_collection_controller.js, app/views/collections/_catches_collection.html.erb, app/views/collections/index.html.erb, app/views/collections/show.html.erb, app/views/shared/_cards_collection.html.erb
front for: index, show and general collec modified
=> Collec front

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_trash_bin.scss, app/views/collections/index.html.erb, app/views/collections/show.html.erb
buttons add and delete a collection done
=> button add and delete modified

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_trash_bin.scss, app/views/collections/index.html.erb, app/views/collections/show.html.erb
button add animal and edit modified to be placed correctly
=> Button front

config/environments/production.rb
setup for domain name foxy-app
=> domain name setup

app/assets/stylesheets/components/_animals.scss, app/assets/stylesheets/components/_cards.scss, app/views/collections/_catches_collection.html.erb, app/views/collections/general.html.erb, app/views/collections/index.html.erb, app/views/collections/show.html.erb
fixed issue with a size but still have an issue with the div that contains the a link
=> issue with div

app/assets/stylesheets/components/_button.scss, app/views/collections/index.html.erb, app/views/collections/new.html.erb, app/views/shared/_cards_collection.html.erb
removed btn around add a collection btn
=> removed btn on add collec

app/assets/stylesheets/users/_show.scss, app/views/users/show.html.erb, db/seeds.rb
- dont pull this
- Profile done
- Seed fix
=> User profile done with extreme skills (thanks mahdi)

app/assets/stylesheets/friends/_show.scss, app/assets/stylesheets/users/_show.scss, app/policies/collection_policy.rb, app/views/friends/show.html.erb, app/views/users/show.html.erb
Friend show done , collections cards for friendshow and user show fixed
=> Friendprofile

app/javascript/controllers/home_controller.js
Signed-off-by: Jessica Roman <jessicaroman.mailpro@gmail.com>
=> fix screen size
